name: "demo parcties"
on: workflow_dispatch
    
jobs:
  demo-practice:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        uses: actions/checkout@v3
      - name: step 2
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: run python
        run: python app.py
